# Generated by Django 6.0.6 on 2026-06-07 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('monthly_price_bdt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_users', models.IntegerField(default=1, help_text='Number of staff accounts allowed')),
                ('max_domains', models.IntegerField(default=1, help_text='Number of custom domains allowed')),
                ('max_storage_gb', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('subdomain', models.SlugField(help_text='e.g., ecompilot.scalexerp.com', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='workspace/logos/')),
                ('primary_color', models.CharField(default='#4338ca', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(help_text='e.g., www.client-brand.com', max_length=100, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('cname_target', models.CharField(default='shops.scalexerp.com', help_text='What user needs to point to', max_length=150)),
                ('verification_txt_name', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_txt_value', models.CharField(blank=True, max_length=255, null=True)),
                ('cloudflare_hostname_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('ssl_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='saas_core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', 'Trial Period'), ('ACTIVE', 'Active & Paid'), ('PAST_DUE', 'Payment Failed / Retrying'), ('SUSPENDED', 'Access Suspended')], default='TRIAL', max_length=20)),
                ('current_period_end', models.DateTimeField()),
                ('current_storage_used_mb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saas_core.subscriptionplan')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='saas_core.workspace')),
            ],
        ),
    ]
