# Generated by Django 6.0.6 on 2026-06-07 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSAppModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Advanced CRM', max_length=100)),
                ('module_code', models.CharField(help_text='e.g., crm (Controls Menu Visibility)', max_length=50, unique=True)),
                ('icon_class', models.CharField(default='fas fa-box', help_text='FontAwesome or SVG class', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('monthly_fee_bdt', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_core_module', models.BooleanField(default=False, help_text='If True, it is free and always visible')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantActiveModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saas_core.saasappmodule')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_modules', to='saas_core.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'module')},
            },
        ),
    ]
