# Generated by Django 6.0.6 on 2026-06-07 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0002_saasappmodule_tenantactivemodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCurrency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g., USD, BDT, EUR', max_length=3, unique=True)),
                ('name', models.CharField(help_text='e.g., US Dollar, Bangladeshi Taka', max_length=50)),
                ('symbol', models.CharField(help_text='e.g., $, ৳, €', max_length=10)),
                ('exchange_rate_to_usd', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id_or_vat', models.CharField(blank=True, help_text='Company VAT/BIN/EIN Number for invoices', max_length=50)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('state_or_division', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('full_address', models.TextField(blank=True, help_text='Street address for official documents')),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('date_format', models.CharField(choices=[('YYYY-MM-DD', 'YYYY-MM-DD (e.g., 2026-12-31)'), ('DD-MM-YYYY', 'DD-MM-YYYY (e.g., 31-12-2026)'), ('MM/DD/YYYY', 'MM/DD/YYYY (e.g., 12/31/2026)')], default='DD-MM-YYYY', max_length=20)),
                ('base_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saas_core.globalcurrency')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localization', to='saas_core.workspace')),
            ],
        ),
    ]
