# Generated by Django 6.0.6 on 2026-06-07 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0003_globalcurrency_workspacesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Link to the error log', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('traceback_data', models.TextField(help_text='Full technical stack trace')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('execution_time_ms', models.FloatField(default=0.0, help_text='Time taken before crash (in ms)')),
                ('memory_usage_mb', models.FloatField(default=0.0, help_text='Peak memory usage (in MB)')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saas_core.workspace')),
            ],
        ),
    ]
