# Generated by Django 6.0.6 on 2026-06-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0004_adminnotification_systemerrorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_identifier', models.CharField(help_text="e.g., 'add_client', 'create_invoice'", max_length=50, unique=True)),
                ('title', models.CharField(default='How to use this page', max_length=150)),
                ('video_embed_url', models.URLField(help_text='YouTube Embed URL (e.g., https://www.youtube.com/embed/dQw4w9WgXcQ)')),
                ('description', models.TextField(blank=True, help_text='Short instructions for the user.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
